# Generated by Django 3.1.1 on 2020-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_alumno', primary_key=True, serialize=False)),
                ('fecha_env', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=40, null=True)),
                ('marca', models.CharField(blank=True, max_length=40, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
