# Generated by Django 3.1.1 on 2020-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higiene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(db_column='id_producto', primary_key=True, serialize=False),
        ),
    ]
