# Generated by Django 3.1.1 on 2020-10-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higiene', '0002_auto_20201021_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id_producto']},
        ),
    ]
